### ISSUE TITLE
Add Proguard Config to Readme

### ISSUE THREAD

**Issue by Jogan** [FuckBoilerplate/RxSocialConnect-Android#12]
I needed to add:

```
-dontwarn javax.xml.bind.DatatypeConverter
-dontwarn org.apache.commons.codec.**
-dontwarn com.ning.http.client.**
```

in order for the library to work with proguard.

**Comment by VictorAlbertos** [comment]
Hi @Jogan 

I don't use proguard, but I doubt this dependency has something to due with RxCache:

`-dontwarn com.ning.http.client.**`

The other two make sense and I'm going to add them to the Readme file.

Thanks 👍

**Comment by VictorAlbertos** [comment]
Hi @Jogan 

I don't use proguard. So I'm going to add them to the readme.

Thanks 👍

**Comment by jbmlaird** [comment]
I'm not sure if OP was using OAuth2 or OAuth1 but in addition to his 3 I had to add 

```
-keep class org.fuckboilerplate.rx_social_connect.internal.persistence.OAuth1AccessToken {
    <fields>;
}
```

for OAuth1.

**Comment by hardwinder** [comment]
I had crash when doing `OAuth2` authentication while having proguard active.
Thanks @jbmlaird for the tip 🍻 
Add this to `proguard-rules` if using `OAuth2`:  
```
-keep class org.fuckboilerplate.rx_social_connect.internal.persistence.OAuth2AccessToken {
    <fields>;
}
```
