### ISSUE TITLE
Extract Gson from dependencies

### ISSUE THREAD

**Issue by olegosipenko** [FuckBoilerplate/RxSocialConnect-Android#8]
Disk.java uses Gson for persistence. But some could use another JSON-converters, such as Jackson, LoganSquare etc. and it would be another dependency and increased pressure on DEX-limit. 
Try to extract these converter as an interface with the ability to provide JSON-converter when registering RxSocialConnect in Application. For example look at Retrofit when you provide instance of Converter when building Retrofit. This way people who use another JSON-converters could use their own converters with your library

**Comment by VictorAlbertos** [comment]
Done. 

Could you check the README file and let me know?

Thanks :)

**Comment by olegosipenko** [comment]
Looks great!
Didn't anticipate that speed in developing 👍

**Comment by VictorAlbertos** [comment]
If you feel like adding a new built-in json converter based on another library, feel free to send a pull request. :)

I'm going to close the issue for now.
